# Generated by Django 2.2.4 on 2019-10-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Это тестовое описание. Бла бла лал алфыл вшфщ тзфы коаие чудные пеньки, сулят нам точно отдохнуть. И на дороге трудной, помогут и друзьям твоим жопу примастить.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
