# Generated by Django 2.2.4 on 2019-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191024_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
