# Generated by Django 2.2.4 on 2019-10-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191031_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
