# Generated by Django 2.2.4 on 2019-11-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191101_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robo',
            name='OutSum',
        ),
        migrations.RemoveField(
            model_name='robo',
            name='created_at',
        ),
    ]
