# Generated by Django 2.2.4 on 2019-11-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191103_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qiwi',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Payment')),
                ('invoice_uid', models.UUIDField()),
            ],
            bases=('core.payment',),
        ),
    ]
